# broadcasting

In [1]:
import numpy as np

In [3]:
a=np.arange(8).reshape(2,4)
b=np.arange(8,16).reshape(2,4)
print(a)
print(b)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [4]:
a+b

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [5]:
c=np.arange(9).reshape(3,3)
d=np.arange(3).reshape(1,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]]


In [6]:
c+d

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

## ability of numpy to treat arrays of diff shapes during operations
- dissimilar arrays honge to broadcasting hota hai
- chota array is broadcasted into bigger one

In [9]:
print(a.shape)
print(b.shape)
print(a+b)

(2, 4)
(2, 4)
[[ 8 10 12 14]
 [16 18 20 22]]


In [10]:
x=np.arange(3).reshape(1,3)
y=np.arange(12).reshape(4,3)
print(x+y)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


## basically one of the two dims needs to be same OR one has to be 1x1

In [13]:
x=np.arange(3,4).reshape(1)
y=np.arange(12).reshape(4,3)
x+y

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [12]:
x1=np.arange(3).reshape(1,3)
y1=np.arange(12).reshape(3,4)
x1+y1
#will show error because dim diff hai

ValueError: operands could not be broadcast together with shapes (1,3) (3,4) 