In [ ]:
# pip install numpy


[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

# ways to create arrays in np

## 1. `np.array()`
- list pass karte hai


In [3]:
arr1=np.array([1,2,3,4])
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


## 2. zeros `np.zeros()` and ones `np.ones()`
- no. of rows and cols passed

In [6]:
arr_zeros=np.zeros((2,3)) #zeros as all elem
print(arr_zeros)

#similaryly for 1's
arr_ones=np.ones((3,2))
print(arr_ones)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


## 3. identity matrix `np.identity()`
- no. of rows passed (idmatrix is nxn)

In [7]:
#identity matrix
arr_identity=np.identity(5)
print(arr_identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 4. range based `np.arange()`
- ismein start, end, steps pass karte hai like normal range() 

In [8]:
#range based
arr6=np.arange(5,10,2) #5 -> begin, 10-> end, 2-> jumps
print(arr6)

[5 7 9]


## 5. linspace `np.linspace()`
- 3 inputs start, end & how many samples to generate
- has more params - 
1. `endpoint=False` which means end wala nahi consider karna 
2. `retstep=True` matlab wo batayega whats the step size

In [13]:
arr7=np.linspace(5,10,10)
print(arr7)

#using retstep
arr7, steps=np.linspace(5,10,10,retstep=True)
print(arr7)
print("steps:",steps)

[ 5.          5.55555556  6.11111111  6.66666667  7.22222222  7.77777778
  8.33333333  8.88888889  9.44444444 10.        ]
[ 5.          5.55555556  6.11111111  6.66666667  7.22222222  7.77777778
  8.33333333  8.88888889  9.44444444 10.        ]
steps: 0.5555555555555556


## 6. copy `copy()`
- seedha dupe banata hai

In [14]:
arr8=arr7.copy()
print(arr8)

[ 5.          5.55555556  6.11111111  6.66666667  7.22222222  7.77777778
  8.33333333  8.88888889  9.44444444 10.        ]


# properties of np arrays
shape, ndim, size, itemsize, dtype, astype()

## 1. shape `.shape`
- output is (rows, cols, no.of arrays)

In [17]:
print(arr1)
print(arr1.shape) #1d array hai

[1 2 3 4]
(4,)


In [21]:
arr9=np.array([[[1,2], [3,4]],[[5,6],[7,8]]])
print(arr9)
print(arr9.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


## 2. ndim `.ndim()`
- dimensions return karta hai

In [22]:
print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [23]:
print(arr9)
print(arr9.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


## 3. size `.size()`
- seedha no. of elems

In [25]:
print(arr9)
print(arr9.size)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8


## 4. data type `.dtype`
- data type batata hai

In [28]:
print(arr_ones)
print(arr_ones.dtype)

print(arr9)
print(arr9.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
int64


## 5. itemsize `.itemsize()`
- ye batata hai size of each item
- dtype ke hisaab se

In [26]:
print(arr_zeros)
print(arr_zeros.itemsize)

[[0. 0. 0.]
 [0. 0. 0.]]
8


## 6. change type `.astype()`
- ek se dusre mein change karega

In [29]:
print(arr9)
print(arr9.dtype)
arr9=arr9.astype('float')
print(arr9)
print(arr9.dtype)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
int64
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]
float64
