In [ ]:
# pip install numpy


[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

# what is ndarray
- n dim array - numpy main data struct
- homogeneous array - all elem of arr are same
- contiguous memory mein store hota hai that's why it's faster
- ml ds etc mein use hota hai

## 1. `np.array(object, dtype)`
- list pass karte hai
- if nested list is passed then multidim array
- default datatype infer karleta hai
- if input is not homo then numpy automatically upcasts it (eg. if `list [1,2,3.5,4]` then dtype will be `float`)


In [3]:
arr1=np.array([1,2,3,4])
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [4]:
arr=np.array([1,2,3.5,4])
print(arr)

[1.  2.  3.5 4. ]


## 2. zeros `np.zeros(shape, dtype)` and ones `np.ones(shape, dtype)`
- no. of rows and cols passed
- used to init weights/dp/image processing etc
- default dtype is `float64`

In [6]:
arr_zeros=np.zeros((2,3)) #zeros as all elem
print(arr_zeros)

#similaryly for 1's
arr_ones=np.ones((3,2))
print(arr_ones)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


## 3. identity matrix `np.identity(, dtype)`
- no. of rows passed (idmatrix is nxn)
- used in matrix multipl, linear algebra, ml

In [7]:
#identity matrix
arr_identity=np.identity(5)
print(arr_identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### related function `np.eye(rows, cols, idx of diag, dtype)`
- allows rectangular matrix
- allows offset
- params:
1. rows = no. of rows
2. cols = no. of cols. optional. default to rows (sq matrix)
3. idx of diag = 0 is main diag, >0 is upper diag, <0 is lower diag
4. dtype

In [8]:
arr=np.eye(2,3, k=1)
arr

array([[0., 1., 0.],
       [0., 0., 1.]])

In [9]:
arr=np.eye(2,3, k=-1)
arr

array([[0., 0., 0.],
       [1., 0., 0.]])

In [10]:
arr=np.eye(4,k=1,dtype=int)
arr

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

## 4. range based `np.arange(start, stop, step, dtype)`
- ismein start, end, steps pass karte hai like normal range() 
- equal space using step size
- stop value NOT included
- can do float steps also

In [8]:
#range based
arr6=np.arange(5,10,2) #5 -> begin, 10-> end, 2-> jumps
print(arr6)

[5 7 9]


## 5. linspace `np.linspace(start, stop, num, endpoint=True, retstep=False, dtype)`
- equally spaces vals in the given interval
- specify the no. of samples reqd instead of step
- `endpoint=True` = includes stop elem
- `retstep=True` = isse 2 things output hote hai `arr` & `step size`
- used to plot graphs, signal processig etc

In [13]:
arr7=np.linspace(5,10,10)
print(arr7)

#using retstep
arr7, steps=np.linspace(5,10,10,retstep=True)
print(arr7)
print("steps:",steps)

[ 5.          5.55555556  6.11111111  6.66666667  7.22222222  7.77777778
  8.33333333  8.88888889  9.44444444 10.        ]
[ 5.          5.55555556  6.11111111  6.66666667  7.22222222  7.77777778
  8.33333333  8.88888889  9.44444444 10.        ]
steps: 0.5555555555555556


## 6. copy `copy()`
- seedha dupe banata hai
- deep copy is created so if this is edited then og array is not modified and vice versa

In [14]:
arr8=arr7.copy()
print(arr8)

[ 5.          5.55555556  6.11111111  6.66666667  7.22222222  7.77777778
  8.33333333  8.88888889  9.44444444 10.        ]


# properties of np arrays
shape, ndim, size, itemsize, dtype, astype()

## 1. shape `.shape`
- output is (rows, cols, no.of arrays)

In [17]:
print(arr1)
print(arr1.shape) #1d array hai

[1 2 3 4]
(4,)


In [21]:
arr9=np.array([[[1,2], [3,4]],[[5,6],[7,8]]])
print(arr9)
print(arr9.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


## 2. ndim `.ndim()`
- dimensions return karta hai

In [22]:
print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [23]:
print(arr9)
print(arr9.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


## 3. size `.size`
- seedha no. of elems

In [25]:
print(arr9)
print(arr9.size)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8


## 4. data type `.dtype`
- data type batata hai
- np arrays are homo

In [28]:
print(arr_ones)
print(arr_ones.dtype)

print(arr9)
print(arr9.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
int64


## 5. itemsize `.itemsize`
- ye batata hai size of each item
- dtype ke hisaab se
```
| dtype   | itemsize |
| int8    |        1 |
| int16   |        2 |
| int32   |        4 |
| int64   |        8 |
| float32 |        4 |
| float64 |        8 |
```


In [26]:
print(arr_zeros)
print(arr_zeros.itemsize)

[[0. 0. 0.]
 [0. 0. 0.]]
8


## 6. change type `.astype()`
- ek se dusre mein change karega

In [29]:
print(arr9)
print(arr9.dtype)
arr9=arr9.astype('float')
print(arr9)
print(arr9.dtype)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
int64
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]
float64
