In [1]:
import numpy as np

## 1. random `np.random()`

In [2]:
np.random.random()

0.053420183110267305

## 2. seed `np.random.seed()`
- isse same hi value return hogi at all times

In [4]:
np.random.seed(1)
np.random.random()

0.417022004702574

## 3. uniform `np.random.uniform()`
- give start and end and usmein se it will give a number
- can give no. of rands reqd also

In [6]:
np.random.uniform(2,4)

2.0002287496346898

In [8]:
np.random.uniform(2,4,3).reshape(1,3)

array([[2.37252042, 2.69112145, 2.79353495]])

## 4. random int `np.random.randint()`

In [10]:
np.random.randint(1,10,10).reshape(5,2)

array([[3, 5],
       [8, 8],
       [2, 8],
       [1, 7],
       [8, 7]], dtype=int32)

## 5. max/min of arr `np.max()/min()`

In [ ]:
a=np.random.randint(1,10,5)
a

array([4, 9, 8, 4, 7], dtype=int32)

In [13]:
np.max(a)

np.int32(9)

In [14]:
np.min(a)

np.int32(4)

In [15]:
#to find index
np.argmax(a)

np.int64(1)

In [16]:
np.argmin(a)

np.int64(0)

## q. replace all odds with -1 using where `np.where(cond, action if cond true, action if cond false)`

In [19]:
a[a%2==1]=-1
a

array([ 4, -1,  8,  4, -1], dtype=int32)

In [ ]:
np.where(a%2==1,-1,a)
#will not change the array

array([ 4, -1,  8,  4, -1], dtype=int32)

In [21]:
a=np.random.randint(1,10,5)
a

array([6, 2, 4, 5, 9], dtype=int32)

In [22]:
np.where(a%2==1,-1,a)

array([ 6,  2,  4, -1, -1], dtype=int32)

In [23]:
a

array([6, 2, 4, 5, 9], dtype=int32)

## 6. percentile `np.percentile()`
- % of the array is less than that

In [31]:
a=np.random.randint(1,40,10)
a

array([24, 37, 28, 38, 20, 39,  9, 33, 35, 11], dtype=int32)

In [32]:
a=np.sort(a)
a

array([ 9, 11, 20, 24, 28, 33, 35, 37, 38, 39], dtype=int32)

In [33]:
np.percentile(a,25)

np.float64(21.0)

In [34]:
np.percentile(a,99)

np.float64(38.91)