In [1]:
import numpy as np

In [2]:
arr=np.arange(20,40).reshape(4,5)
arr

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [3]:
arr[0]

array([20, 21, 22, 23, 24])

In [4]:
arr[0][3]

np.int64(23)

In [5]:
#sabke saath check karega
arr>30

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [6]:
arr[arr>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

## this is indexiing using boolean arrays/filtering
- returns all true values
- scalable hai

In [10]:
arr[(arr>15 ) & (arr%2==0)]
#bool pe humesha bitwise & for AND

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [12]:
arr[(arr>15 ) & (arr%2==0)]=1
arr

array([[ 1, 21,  1, 23,  1],
       [25,  1, 27,  1, 29],
       [ 1, 31,  1, 33,  1],
       [35,  1, 37,  1, 39]])