In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

In [3]:
print(arr1-arr2)

[-3 -3 -3 -3 -3 -3]


In [4]:
print(arr1+arr2)

[ 5  7  9 11 13 15]


In [5]:
print(arr1*arr2)

[ 4 10 18 28 40 54]


In [6]:
print(arr1*2)

[ 2  4  6  8 10 12]


In [7]:
arr2>3 #jidhar condition true hai udhar true aayega nahi to false

array([ True,  True,  True,  True,  True,  True])

In [8]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [9]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [10]:
arr1.dot(arr2)

np.int64(154)

In [11]:
arr1.max(), arr2.max(), arr3.max(), arr4.max()

(np.int64(6), np.int64(9), np.int64(5), np.int64(11))

In [13]:
#using axis to find miin or max of all rows/cols
arr3.min(axis=1)
#isse all columns ke min values ka array output hoga

array([0, 3])

In [14]:
#same for sum etc
arr4.sum(axis=0)
#this will sum all rows individually and return arr of the sum

array([24, 27])

In [ ]:
arr4.mean(axis=0)

array([8., 9.])

In [17]:
arr3.std()

np.float64(1.707825127659933)

In [18]:
np.median(arr2)

np.float64(6.5)

In [19]:
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

In [20]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

### aur bhi operations hai 
### to be explored