In [2]:
import numpy as np

In [3]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [4]:
arr3.ndim

2

## 1. ravel `.ravel()`
- nditer() jaise kardeta hai
- flattens

In [5]:
arr3.ravel() #flatten kardeta hai

array([0, 1, 2, 3, 4, 5])

## 2. transpose `.transpose()`
- transpose kardeta hai
- row ka col, col ka row

## 3. stacking `np.hstack((arrays))` or `np.vstack((arrays))`
- stack karte hai arrays ko
- shapes must match

In [6]:
arr5=np.arange(6).reshape(2,3)
arr6=np.arange(12,18).reshape(2,3)

In [7]:
np.hstack((arr5,arr6))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [8]:
np.vstack((arr5,arr6))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

## 4. splitting `np.hsplit()` or `np.vsplit()`

In [9]:
arr5

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
np.hsplit(arr5,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [11]:
np.vsplit(arr5,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]